# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=63, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('date', models.DateField()),
                ('draft', models.BooleanField(default=True)),
                ('pop', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=31, unique=True)),
                ('name', models.CharField(max_length=127)),
                ('bio', models.CharField(max_length=1023)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=31, unique=True)),
                ('name', models.CharField(max_length=127)),
                ('on_navbar', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(to='_bergi.Author'),
        ),
        migrations.AddField(
            model_name='article',
            name='cats',
            field=models.ManyToManyField(to='_bergi.Cat'),
        ),
    ]
