# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-06 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_bergi', '0031_gin_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(related_name='articles', to='_bergi.Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cats',
            field=models.ManyToManyField(related_name='articles', to='_bergi.Cat'),
        ),
    ]
