# Generated by Django 2.2.6 on 2019-11-03 21:39

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('_bergi', '0032_auto_20180406_0139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-featured', '-date', '-pk']},
        ),
        migrations.AddField(
            model_name='article',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=martor.models.MartorField(),
        ),
    ]
